# Generated by Django 2.0.3 on 2018-03-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of prefix')),
                ('abbrev', models.CharField(max_length=10, verbose_name='abbreviation of prefix')),
                ('val', models.FloatField(verbose_name='value of prefix')),
            ],
        ),
        migrations.CreateModel(
            name='unitOfMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of unit')),
                ('abbrev', models.CharField(max_length=10, verbose_name='abbreviation of unit')),
                ('cat', models.CharField(max_length=100, verbose_name='unit category')),
                ('val', models.FloatField(verbose_name='value of unit relative to metric standard')),
            ],
        ),
    ]
