# Generated by Django 2.0.3 on 2018-03-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='abbrev',
            field=models.CharField(blank=True, max_length=10, verbose_name='abbreviation of unit'),
        ),
    ]
